system {
    host-name Borda-Juniper;
    root-authentication {
        plain-text-password-value "Juniper123";
    }
}
interfaces {
    ge-0/0/0 {
        description "Link-Operadora-1";
        unit 0 {
            family inet {
                address 100.64.1.2/30;
            }
        }
    }
    ge-0/0/1 {
        description "Link-Operadora-2";
        unit 0 {
            family inet {
                address 100.64.2.2/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 200.100.0.1/22;
            }
        }
    }
}
routing-options {
    autonomous-system 65100;
}
protocols {
    bgp {
        group TRANSITO {
            type external;
            neighbor 100.64.1.1 {
                peer-as 65001;
                description "Upstream-Operadora-1";
            }
            neighbor 100.64.2.1 {
                peer-as 65002;
                description "Upstream-Operadora-2";
            }
        }
    }
}
