frr version 10.0
frr defaults traditional
hostname operadora2
log stdout
!
interface eth1
 description Link-Borda-FRR
 ip address 100.64.2.1/30
exit
!
interface eth2
 description Link-Borda-Mikrotik
 ip address 100.64.12.1/30
exit
!
interface eth3
 description Link-Borda-Cisco
 ip address 100.64.22.1/30
exit
!
interface eth4
 description Link-Borda-Juniper
 ip address 100.64.32.1/30
exit
!
interface eth5
 description Link-Borda-Huawei
 ip address 100.64.42.1/30
exit
!
route-map PERMIT_ALL permit 10
exit
!
router bgp 65002
 bgp router-id 100.64.2.1
 no bgp ebgp-requires-policy
 ! 1. FRR (AS 65100)
 neighbor 100.64.2.2 remote-as 65100
 neighbor 100.64.2.2 description "ISP-FRR"
 ! 2. MikroTik (AS 65101)
 neighbor 100.64.12.2 remote-as 65101
 neighbor 100.64.12.2 description "ISP-MikroTik"
 ! 3. Cisco IOL (AS 65102)
 neighbor 100.64.22.2 remote-as 65102
 neighbor 100.64.22.2 description "ISP-Cisco"
 ! 4. Juniper Junos (AS 65103)
 neighbor 100.64.32.2 remote-as 65103
 neighbor 100.64.32.2 description "ISP-Juniper"
 ! 5. Huawei VRP (AS 65104)
 neighbor 100.64.42.2 remote-as 65104
 neighbor 100.64.42.2 description "ISP-Huawei"
 !
 address-family ipv4 unicast
  network 0.0.0.0/0
  neighbor 100.64.2.2 activate
  neighbor 100.64.2.2 default-originate
  neighbor 100.64.2.2 route-map PERMIT_ALL in
  neighbor 100.64.2.2 route-map PERMIT_ALL out
  !
  neighbor 100.64.12.2 activate
  neighbor 100.64.12.2 default-originate
  neighbor 100.64.12.2 route-map PERMIT_ALL in
  neighbor 100.64.12.2 route-map PERMIT_ALL out
  !
  neighbor 100.64.22.2 activate
  neighbor 100.64.22.2 default-originate
  neighbor 100.64.22.2 route-map PERMIT_ALL in
  neighbor 100.64.22.2 route-map PERMIT_ALL out
  !
  neighbor 100.64.32.2 activate
  neighbor 100.64.32.2 default-originate
  neighbor 100.64.32.2 route-map PERMIT_ALL in
  neighbor 100.64.32.2 route-map PERMIT_ALL out
  !
  neighbor 100.64.42.2 activate
  neighbor 100.64.42.2 default-originate
  neighbor 100.64.42.2 route-map PERMIT_ALL in
  neighbor 100.64.42.2 route-map PERMIT_ALL out
 exit-address-family
exit
!
line vty
!
