frr version 10.0
frr defaults traditional
hostname borda-isp
log stdout
!
interface eth1
 description Link-Operadora-1
 ip address 100.64.1.2/30
exit
!
interface eth2
 description Link-Operadora-2
 ip address 100.64.2.2/30
exit
!
interface lo
 description Bloco-ISP
 ip address 200.100.0.1/22
exit
!
# =============================================================
# ROUTE-MAPS / POLÍTICAS PRÉ-CONFIGURADAS DE ENGENHARIA DE TRÁFEGO
# =============================================================
route-map PERMIT_ALL permit 10
exit
!
route-map PREPEND_1X permit 10
 set as-path prepend 65100
exit
!
route-map PREPEND_2X permit 10
 set as-path prepend 65100 65100
exit
!
route-map PREPEND_3X permit 10
 set as-path prepend 65100 65100 65100
exit
!
route-map PREPEND_5X permit 10
 set as-path prepend 65100 65100 65100 65100 65100
exit
!
route-map PREFER_LOCAL permit 10
 set local-preference 200
exit
!
route-map BACKUP_LOCAL permit 10
 set local-preference 80
exit
!
# =============================================================
# PROCESSO BGP Borda ISP (AS 65100)
# =============================================================
router bgp 65100
 bgp router-id 100.64.1.2
 no bgp ebgp-requires-policy
 neighbor 100.64.1.1 remote-as 65001
 neighbor 100.64.1.1 description Upstream-Operadora-1
 neighbor 100.64.2.1 remote-as 65002
 neighbor 100.64.2.1 description Upstream-Operadora-2
 !
 address-family ipv4 unicast
  network 200.100.0.0/22
  neighbor 100.64.1.1 activate
  neighbor 100.64.1.1 route-map PERMIT_ALL in
  neighbor 100.64.1.1 route-map PERMIT_ALL out
  neighbor 100.64.2.1 activate
  neighbor 100.64.2.1 route-map PERMIT_ALL in
  neighbor 100.64.2.1 route-map PERMIT_ALL out
 exit-address-family
exit
!
line vty
!
